import { SubmitFormField, SubmitFormFieldType } from '@/types/hackathon-stage';

export const BASE_SUBMIT_FORM_FIELDS = {
  project_name: {
    label: 'Project Name',
    field: {
      id: 'project_name',
      type: SubmitFormFieldType.Text,
      label: 'Project Name',
      placeholder: 'Enter the project name',
      description: 'The name of the project being submitted.',
      maxCharacters: 40,
      predefinedField: true,
      required: true,
    },
  },
  short_description: {
    label: 'Short Description',
    field: {
      id: 'short_description',
      type: SubmitFormFieldType.Text,
      label: 'Short Description',
      placeholder: 'Enter a short description',
      description: 'A brief overview of the project.',
      maxCharacters: 100,
      predefinedField: true,
      required: true,
    },
  },
  full_description: {
    label: 'Full Description',
    field: {
      id: 'full_description',
      type: SubmitFormFieldType.Text,
      label: 'Full Description',
      placeholder: 'Enter a full description',
      description: 'A detailed overview of the project.',
      maxCharacters: 200,
      predefinedField: true,
      required: true,
    },
  },
  deployed_addresses: {
    label: 'Deployed Addresses',
    field: {
      id: 'deployed_addresses',
      type: SubmitFormFieldType.Link,
      label: 'Deployed Addresses',
      placeholder: 'Enter a contract address or URL',
      description: 'Addresses or links where the project is deployed. Each entry can have an optional tag.',
      predefinedField: true,
      required: false,
    },
  },
  categories: {
    label: 'Categories',
    field: {
      id: 'categories',
      type: SubmitFormFieldType.MultiSelect,
      label: 'Categories',
      description: 'Select the categories that best describe your project.',
      placeholder: 'Select categories',
      predefinedField: true,
      required: true,
      options: ['Consumer', 'DeFi', 'Enterprise', 'Developer Tooling', 'RWA', 'Gaming', 'Social'],
    },
  },
  github_repository: {
    label: 'GitHub Repository',
    field: {
      id: 'github_repository',
      type: SubmitFormFieldType.Link,
      label: 'GitHub Repository',
      description: 'Must be a valid GitHub repository URL (e.g., https://github.com/username/repo)',
      placeholder: 'Enter the GitHub repository URL',
      maxLinks: 1,
      predefinedField: true,
      required: true,
    },
  },
  demo_link: {
    label: 'Demo and Other Links',
    field: {
      id: 'demo_link',
      type: SubmitFormFieldType.Link,
      label: 'Demo and Other Links',
      description: 'Paste any project links (e.g., https://github.com/username/repo)',
      placeholder: 'Provide live demo, presentation, or any other relevant links',
      maxLinks: 10,
      predefinedField: true,
      required: true,
    },
  },
  explanation: {
    label: 'How It’s Made',
    field: {
      id: 'explanation',
      type: SubmitFormFieldType.Text,
      label: 'How It’s Made',
      description: 'Explain how your project works under the hood. Tech stack integrations, architecture decisions, etc.',
      placeholder: ' Describe the tech stack, architecture, and any unique technical aspects of your project.',
      predefinedField: true,
      maxCharacters: 1000,
      required: true,
    },
  },
  consent_sharing: {
    label: 'Consent to Sharing',
    field: {
      id: 'consent_sharing',
      type: SubmitFormFieldType.Boolean,
      label: 'I consent to my project being shared publicly',
      description: 'Required. Authorizes the organizers to showcase this project.',
      predefinedField: true,
      required: true,
    },
  },
  is_preexisting_idea: {
    label: 'Pre-existing Idea',
    field: {
      id: 'is_preexisting_idea',
      type: SubmitFormFieldType.Boolean,
      label: 'Is this a pre-existing project or idea?',
      description: 'Indicates whether the project existed before the hackathon.',
      predefinedField: true,
      required: false,
    },
  },
  tracks: {
    label: 'Tracks',
    field: {
      id: 'tracks',
      type: SubmitFormFieldType.MultiSelect,
      label: 'Tracks',
      description: 'Select the tracks your project is participating in.',
      placeholder: 'Select tracks',
      predefinedField: true,
      required: false,
      options: [],
    },
  },
  tech_stack: {
    label: 'Tech Stack',
    field: {
      id: 'tech_stack',
      type: SubmitFormFieldType.MultiSelect,
      label: 'Tech Stack',
      description: 'Select the technologies used to build your project.',
      placeholder: 'Select tech stack',
      predefinedField: true,
      required: false,
      options: [],
    },
  },
  screenshots: {
    label: 'Screenshots',
    field: {
      id: 'screenshots',
      type: SubmitFormFieldType.Image,
      label: 'Screenshots',
      description: 'Upload up to 5 screenshots of your project (max 2 MB each).',
      predefinedField: true,
      required: false,
      maxImages: 5,
      maxSizeMb: 2,
    },
  },
  logo_url: {
    label: 'Logo',
    field: {
      id: 'logo_url',
      type: SubmitFormFieldType.Image,
      label: 'Project Logo',
      description: 'Upload a logo for your project (max 2 MB).',
      predefinedField: true,
      required: false,
      maxImages: 1,
      maxSizeMb: 2,
    },
  },
  cover_url: {
    label: 'Cover Image',
    field: {
      id: 'cover_url',
      type: SubmitFormFieldType.Image,
      label: 'Cover Image',
      description: 'Upload a cover image for your project (max 2 MB).',
      predefinedField: true,
      required: false,
      maxImages: 1,
      maxSizeMb: 2,
    },
  },
  demo_video_link: {
    label: 'Demo Video',
    field: {
      id: 'demo_video_link',
      type: SubmitFormFieldType.Link,
      label: 'Demo Video',
      description: 'Link to a demo video (e.g., YouTube, Loom).',
      placeholder: 'Enter the demo video URL',
      maxLinks: 1,
      predefinedField: true,
      required: false,
    },
  },
  socials: {
    label: 'Social Links',
    field: {
      id: 'socials',
      type: SubmitFormFieldType.Link,
      label: 'Social Links',
      description: 'Links to the project social profiles (X, Discord, etc.).',
      placeholder: 'Enter a social profile URL',
      maxLinks: 5,
      predefinedField: true,
      required: false,
    },
  },
  website: {
    label: 'Website',
    field: {
      id: 'website',
      type: SubmitFormFieldType.Link,
      label: 'Website',
      description: 'Project website URL.',
      placeholder: 'Enter the website URL',
      maxLinks: 1,
      predefinedField: true,
      required: false,
    },
  },
} satisfies Record<
  string,
  {
    label: string;
    field: SubmitFormField;
  }
>;

export type BaseSubmitFormFieldKey = keyof typeof BASE_SUBMIT_FORM_FIELDS;
